### PR TITLE
757 sql reformatting finetune sqlfluff

### LINKED ISSUE #757: sql reformatting
### Describe the Bug

To include this in CI, we will need to fix all these errors first.

### Steps to Reproduce the Problem

root folder of the project

```sh
pre-commit run sqlfluff-fix -a
```

### Expected Result

✔️ 

### Actual Result

FAIL

### PermaplanT version

master

### Operating System

devcontainer rust:1.67.1-slim image

### Additional info/logs

image

### PR DESCRIPTION
**Pull request by temmey**
closes #757

## Basics

- [x] I added a line to [/doc/CHANGELOG.md](/doc/CHANGELOG.md)
- [x] The PR is rebased with current master.
- [x] Details of what you changed are in commit messages.
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildserver is happy.

## Checklist

- [x] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed the introduction tour
- [x] I wrote migrations in a way that they are compatible with already present data
- [x] I fixed all affected decisions
- [ ] I added unit tests for my code
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](https://github.com/ElektraInitiative/PermaplanT/blob/master/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [x] Code is conforming to [our Architecture](/doc/architecture)
- [x] Code is conforming to [our Guidelines](/doc/guidelines)
      (exceptions are documented)
- [x] Code is consistent to [our Design Decisions](/doc/decisions)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] Examples are well chosen and understandable

### CODE REVIEW

File: backend/migrations/2023-07-01-152628_squashed_setup/up.sql [hunk 1]
```diff
@@ -176,93 +176,93 @@ END;
...
+    name TEXT NOT NULL,
+    creation_date DATE NOT NULL,
+    deletion_date DATE,
+    last_visit DATE,
+    is_inactive BOOLEAN NOT NULL,
+    zoom_factor SMALLINT NOT NULL,
+    honors SMALLINT NOT NULL,
+    visits SMALLINT NOT NULL,
+    harvested SMALLINT NOT NULL,
+    privacy PRIVACY_OPTION NOT NULL,
```
Comment (markus2330) [inline backend/migrations/2023-07-01-152628_squashed_setup/up.sql:205]: This is not according to current database guidelines, we wrote: "use `snake_case` for everything except database keywords, which should be `UPPERCASE`". So it should be `privacy_option`. Isn't this supported by sqlfluff?

Btw. even for INTEGER it is questionable if it is a keyword, according to https://www.postgresql.org/docs/current/sql-keywords-appendix.html INTEGER is non-reserved (cannot be function or type).

Comment (temmey) [reply backend/migrations/2023-07-01-152628_squashed_setup/up.sql]: > This is not according to current database guidelines, we wrote: "use `snake_case` for everything except database keywords, which should be `UPPERCASE`". So it should be `privacy_option`. Isn't this supported by sqlfluff?

No, sadly it's not, but I applied it for now by manually changing the rules.
https://docs.sqlfluff.com/en/stable/rules.html#rule-capitalisation.types


> Btw. even for INTEGER it is questionable if it is a keyword, according to https://www.postgresql.org/docs/current/sql-keywords-appendix.html INTEGER is non-reserved (cannot be function or type).

I could make it snake_case, but since it's a standard keyword, I would keep it uppercase.

**Review by absurd-turtle — APPROVED** [review]

**Comment by markus2330** [comment]
@4ydan what do you think about running sqlfluff twice with different configs? Is this even possible to have in pre-commit? (In CI it would work.)

@temmey can you create an upstream bug report, maybe there is some way we didn't see.

**Comment by temmey** [comment]
> @4ydan what do you think about running sqlfluff twice with different configs? Is this even possible to have in pre-commit? (In CI it would work.)

We can solve it by creating a new entry into `.pre-commit-config.yaml` and copying the config `.sqlfluff`. That way, it will generate errors though, which will be fixed right after.

**Comment by temmey** [comment]
> @temmey can you create an upstream bug report, maybe there is some way we didn't see. Please link from here when you created the issue.

https://github.com/sqlfluff/sqlfluff/issues/5049

**Comment by markus2330** [comment]
> https://github.com/sqlfluff/sqlfluff/issues/5049

Great job, let us see what they say, maybe we can go the direct way without workarounds in our pre-commit/CI configs.

**Comment by 4ydan** [comment]
> @4ydan what do you think about running sqlfluff twice with different configs? Is this even possible to have in pre-commit? (In CI it would work.)

Yes as temmy said, we could write a second sqlfluff hook with a different id and make sure they dont run over the same files.

**Review by 4ydan — APPROVED** [review]
Pre-commit looks good now, but isnt it possible to just have two different hooks in there instead of manuall shifting something around in the config file?

**Comment by temmey** [comment]
If we want to do it like that, I will write a commit for it. Manual shifting is a bad solution.

File: doc/decisions/example_migrations/taxonomy-ranks-and-concrete-plants/example_queries.sql.md [hunk 2]
```diff
@@ -0,0 +1,280 @@
+--
+-- Example: Relationships
+--
+-- For this example we use the following notation
```
Comment (badnames) [inline doc/decisions/example_migrations/taxonomy-ranks-and-concrete-plants/example_queries.sql.md:4]:
```suggestion
-- For this example we use the following notation:
```

File: doc/decisions/example_migrations/taxonomy-ranks-and-concrete-plants/example_queries.sql.md [hunk 3]
```diff
@@ -0,0 +1,280 @@
...
+-- companion "<->"
+-- antagonist ">-<"
+-- Consider the following relationships between plants:
```
Comment (badnames) [inline doc/decisions/example_migrations/taxonomy-ranks-and-concrete-plants/example_queries.sql.md:7]:
```suggestion
--
-- Consider the following relationships between plants:
```

File: doc/decisions/example_migrations/taxonomy-ranks-and-concrete-plants/example_queries.sql.md [hunk 4]
```diff
@@ -0,0 +1,280 @@
...
+-- Radish <-> carrot
+-- Radish <-> potato
+-- Carrot >-< potato
+-- Marigold <-> carrot
+-- Marigold <-> radish
+--
+-- We want to plant carrots and radish and get suggestions for it.
```
Comment (badnames) [inline doc/decisions/example_migrations/taxonomy-ranks-and-concrete-plants/example_queries.sql.md:14]:
```suggestion
-- We want to plant carrots and radishes and get suggestions for it.
```

File: doc/decisions/example_migrations/taxonomy-ranks-and-concrete-plants/example_queries.sql.md [hunk 5]
```diff
@@ -0,0 +1,280 @@
...
+-- Radish <-> potato
+('companion', 1, (SELECT id FROM radish_species), (SELECT id FROM potato_species)),
+-- Carrot >-< potato
+('antagonist', 1, (SELECT id FROM carrot_species), (SELECT id FROM potato_species)),
+-- Marigold <-> carrot
+('companion', 1, (SELECT id FROM marigold_species), (SELECT id FROM carrot_species)),
+-- Marigold <-> radish
+('companion', 1, (SELECT id FROM marigold_species), (SELECT id FROM radish_species));
+
+## -- Let's look for companions that go well with carrot and radish
```
Comment (badnames) [inline doc/decisions/example_migrations/taxonomy-ranks-and-concrete-plants/example_queries.sql.md:169]: Did you intend to make this a heading?

File: doc/decisions/example_migrations/normalized-plants-and-ranks/example_queries.sql.md [hunk 6]
```diff
@@ -0,0 +1,254 @@
+--
+-- Example: Relationships
+--
+-- For this example we use the following notation
```
Comment (badnames) [inline doc/decisions/example_migrations/normalized-plants-and-ranks/example_queries.sql.md:4]:
```suggestion
-- For this example we use the following notation:
```

File: doc/decisions/example_migrations/normalized-plants-and-ranks/example_queries.sql.md [hunk 7]
```diff
@@ -0,0 +1,254 @@
...
+-- companion "<->"
+-- antagonist ">-<"
+-- Consider the following relationships between plants:
```
Comment (badnames) [inline doc/decisions/example_migrations/normalized-plants-and-ranks/example_queries.sql.md:7]:
```suggestion
--
-- Consider the following relationships between plants:
```

**Review by badnames — APPROVED** [review]
Good work! I just noticed a few minor styling and grammar mistakes.

File: doc/decisions/example_migrations/taxonomy-ranks-and-concrete-plants/example_queries.sql.md (hunk 2 above)
Comment (temmey) [reply doc/decisions/example_migrations/taxonomy-ranks-and-concrete-plants/example_queries.sql.md:4]: will be removed with #793

File: doc/decisions/example_migrations/taxonomy-ranks-and-concrete-plants/example_queries.sql.md (hunk 3 above)
Comment (temmey) [reply doc/decisions/example_migrations/taxonomy-ranks-and-concrete-plants/example_queries.sql.md:7]: will be removed with #793

File: doc/decisions/example_migrations/taxonomy-ranks-and-concrete-plants/example_queries.sql.md [hunk 8]
```diff
@@ -0,0 +1,280 @@
...
+-- antagonist ">-<"
+-- Consider the following relationships between plants:
+-- Radish <-> carrot
+-- Radish <-> potato
+-- Carrot >-< potato
+-- Marigold <-> carrot
+-- Marigold <-> radish
+--
+-- We want to plant carrots and radish and get suggestions for it.
+-- When looking for companions we would expect the result just to be marigold.
```
[the remark this answers is not in the document]
Comment (temmey) [reply doc/decisions/example_migrations/taxonomy-ranks-and-concrete-plants/example_queries.sql.md:15]: will be removed with #793

File: doc/decisions/example_migrations/taxonomy-ranks-and-concrete-plants/example_queries.sql.md (hunk 5 above)
Comment (temmey) [reply doc/decisions/example_migrations/taxonomy-ranks-and-concrete-plants/example_queries.sql.md:169]: will be removed with #793

File: doc/decisions/example_migrations/taxonomy-ranks-and-concrete-plants/example_queries.sql.md (hunk 4 above)
Comment (temmey) [reply doc/decisions/example_migrations/taxonomy-ranks-and-concrete-plants/example_queries.sql.md:14]: will be removed with #793

File: doc/decisions/example_migrations/normalized-plants-and-ranks/example_queries.sql.md (hunk 6 above)
Comment (temmey) [reply doc/decisions/example_migrations/normalized-plants-and-ranks/example_queries.sql.md:4]: will be removed with #793

File: doc/decisions/example_migrations/normalized-plants-and-ranks/example_queries.sql.md (hunk 7 above)
Comment (temmey) [reply doc/decisions/example_migrations/normalized-plants-and-ranks/example_queries.sql.md:7]: will be removed with #793

**Comment by 4ydan** [comment]
Isnt this now doing exactly what we want in one config file?

**Comment by markus2330** [comment]
Great job, finally done! I am happy with these a bit relaxed rules. The tool also shouldn't get in the way too much.
